#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openmpi
Version  : 2.1.3
Release  : 19
URL      : https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.3.tar.bz2
Source0  : https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.3.tar.bz2
Summary  : A powerful implementation of MPI/SHMEM
Group    : Development/Tools
License  : BSD-3-Clause BSD-3-Clause-Clear Intel
Requires: openmpi-bin = %{version}-%{release}
Requires: openmpi-data = %{version}-%{release}
Requires: openmpi-lib = %{version}-%{release}
Requires: openmpi-license = %{version}-%{release}
Requires: openmpi-man = %{version}-%{release}
BuildRequires : db-dev
BuildRequires : flex
BuildRequires : gfortran
BuildRequires : grep
BuildRequires : hwloc-dev
BuildRequires : libpciaccess-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(zlib)
BuildRequires : sed
BuildRequires : systemd-dev
BuildRequires : valgrind
Patch1: root.patch

%description
Open MPI is an open source implementation of the Message Passing
Interface specification (http://www.mpi-forum.org/) developed and
maintained by a consortium of research, academic, and industry
partners.

Open MPI also includes an implementation of the OpenSHMEM parallel
programming API (http://www.openshmem.org/).  OpenSHMEM is a
Partitioned Global Address Space (PGAS) abstraction layer, which
provides fast inter-process communication using one-sided
communication techniques.

This RPM contains all the tools necessary to compile, link, and run
Open MPI and OpenSHMEM jobs.

%package bin
Summary: bin components for the openmpi package.
Group: Binaries
Requires: openmpi-data = %{version}-%{release}
Requires: openmpi-license = %{version}-%{release}
Requires: openmpi-man = %{version}-%{release}

%description bin
bin components for the openmpi package.


%package data
Summary: data components for the openmpi package.
Group: Data

%description data
data components for the openmpi package.


%package dev
Summary: dev components for the openmpi package.
Group: Development
Requires: openmpi-lib = %{version}-%{release}
Requires: openmpi-bin = %{version}-%{release}
Requires: openmpi-data = %{version}-%{release}
Provides: openmpi-devel = %{version}-%{release}

%description dev
dev components for the openmpi package.


%package lib
Summary: lib components for the openmpi package.
Group: Libraries
Requires: openmpi-data = %{version}-%{release}
Requires: openmpi-license = %{version}-%{release}

%description lib
lib components for the openmpi package.


%package license
Summary: license components for the openmpi package.
Group: Default

%description license
license components for the openmpi package.


%package man
Summary: man components for the openmpi package.
Group: Default

%description man
man components for the openmpi package.


%prep
%setup -q -n openmpi-2.1.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542410883
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error   -Wl,-z,max-page-size=0x1000 -m64 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
unset LDFLAGS
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -ffat-lto-objects -flto=4 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
%configure --disable-static --enable-branch-probabilities \
--enable-builtin-atomics \
--with-wrapper-cflags-prefix="-march=native -O3" \
--with-wrapper-cxxflags-prefix="-march=native -O3" \
--with-wrapper-fcflags-prefix="-march=native -O3"
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542410883
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/openmpi
cp LICENSE %{buildroot}/usr/share/package-licenses/openmpi/LICENSE
cp contrib/dist/mofed/debian/copyright %{buildroot}/usr/share/package-licenses/openmpi/contrib_dist_mofed_debian_copyright
cp opal/mca/event/libevent2022/libevent/LICENSE %{buildroot}/usr/share/package-licenses/openmpi/opal_mca_event_libevent2022_libevent_LICENSE
cp opal/mca/hwloc/hwloc1112/hwloc/COPYING %{buildroot}/usr/share/package-licenses/openmpi/opal_mca_hwloc_hwloc1112_hwloc_COPYING
cp opal/mca/pmix/pmix112/pmix/LICENSE %{buildroot}/usr/share/package-licenses/openmpi/opal_mca_pmix_pmix112_pmix_LICENSE
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/mpi.mod
/usr/lib64/mpi_ext.mod
/usr/lib64/mpi_f08.mod
/usr/lib64/mpi_f08_callbacks.mod
/usr/lib64/mpi_f08_ext.mod
/usr/lib64/mpi_f08_interfaces.mod
/usr/lib64/mpi_f08_interfaces_callbacks.mod
/usr/lib64/mpi_f08_types.mod
/usr/lib64/pmpi_f08_interfaces.mod

%files bin
%defattr(-,root,root,-)
/usr/bin/mpiCC
/usr/bin/mpic++
/usr/bin/mpicc
/usr/bin/mpicxx
/usr/bin/mpiexec
/usr/bin/mpif77
/usr/bin/mpif90
/usr/bin/mpifort
/usr/bin/mpirun
/usr/bin/ompi-clean
/usr/bin/ompi-dvm
/usr/bin/ompi-ps
/usr/bin/ompi-server
/usr/bin/ompi-submit
/usr/bin/ompi-top
/usr/bin/ompi_info
/usr/bin/opal_wrapper
/usr/bin/orte-clean
/usr/bin/orte-dvm
/usr/bin/orte-info
/usr/bin/orte-ps
/usr/bin/orte-server
/usr/bin/orte-submit
/usr/bin/orte-top
/usr/bin/ortecc
/usr/bin/orted
/usr/bin/orterun
/usr/bin/oshcc
/usr/bin/oshfort
/usr/bin/oshmem_info
/usr/bin/oshrun
/usr/bin/shmemcc
/usr/bin/shmemfort
/usr/bin/shmemrun

%files data
%defattr(-,root,root,-)
/usr/share/openmpi/amca-param-sets/example.conf
/usr/share/openmpi/help-btl-vader.txt
/usr/share/openmpi/help-coll-sync.txt
/usr/share/openmpi/help-dash-host.txt
/usr/share/openmpi/help-errmgr-base.txt
/usr/share/openmpi/help-ess-base.txt
/usr/share/openmpi/help-hostfile.txt
/usr/share/openmpi/help-mca-base.txt
/usr/share/openmpi/help-mca-bml-r2.txt
/usr/share/openmpi/help-mca-coll-base.txt
/usr/share/openmpi/help-mca-osc-base.txt
/usr/share/openmpi/help-mca-var.txt
/usr/share/openmpi/help-mpi-api.txt
/usr/share/openmpi/help-mpi-btl-base.txt
/usr/share/openmpi/help-mpi-btl-sm.txt
/usr/share/openmpi/help-mpi-btl-tcp.txt
/usr/share/openmpi/help-mpi-coll-sm.txt
/usr/share/openmpi/help-mpi-common-sm.txt
/usr/share/openmpi/help-mpi-errors.txt
/usr/share/openmpi/help-mpi-pml-ob1.txt
/usr/share/openmpi/help-mpi-runtime.txt
/usr/share/openmpi/help-mpool-base.txt
/usr/share/openmpi/help-oob-base.txt
/usr/share/openmpi/help-oob-tcp.txt
/usr/share/openmpi/help-opal-hwloc-base.txt
/usr/share/openmpi/help-opal-runtime.txt
/usr/share/openmpi/help-opal-shmem-mmap.txt
/usr/share/openmpi/help-opal-shmem-posix.txt
/usr/share/openmpi/help-opal-shmem-sysv.txt
/usr/share/openmpi/help-opal-timer-linux.txt
/usr/share/openmpi/help-opal-util.txt
/usr/share/openmpi/help-opal-wrapper.txt
/usr/share/openmpi/help-opal_info.txt
/usr/share/openmpi/help-orte-clean.txt
/usr/share/openmpi/help-orte-filem-raw.txt
/usr/share/openmpi/help-orte-info.txt
/usr/share/openmpi/help-orte-odls-base.txt
/usr/share/openmpi/help-orte-odls-default.txt
/usr/share/openmpi/help-orte-ps.txt
/usr/share/openmpi/help-orte-rmaps-base.txt
/usr/share/openmpi/help-orte-rmaps-md.txt
/usr/share/openmpi/help-orte-rmaps-ppr.txt
/usr/share/openmpi/help-orte-rmaps-resilient.txt
/usr/share/openmpi/help-orte-rmaps-rr.txt
/usr/share/openmpi/help-orte-rmaps-seq.txt
/usr/share/openmpi/help-orte-rtc-base.txt
/usr/share/openmpi/help-orte-runtime.txt
/usr/share/openmpi/help-orte-server.txt
/usr/share/openmpi/help-orte-top.txt
/usr/share/openmpi/help-orted.txt
/usr/share/openmpi/help-orterun.txt
/usr/share/openmpi/help-oshmem-info.txt
/usr/share/openmpi/help-oshmem-memheap.txt
/usr/share/openmpi/help-oshmem-spml-yoda.txt
/usr/share/openmpi/help-oshmem-sshmem-mmap.txt
/usr/share/openmpi/help-oshmem-sshmem-sysv.txt
/usr/share/openmpi/help-oshmem-sshmem.txt
/usr/share/openmpi/help-plm-base.txt
/usr/share/openmpi/help-plm-rsh.txt
/usr/share/openmpi/help-plm-slurm.txt
/usr/share/openmpi/help-pmix-base.txt
/usr/share/openmpi/help-ras-base.txt
/usr/share/openmpi/help-ras-simulator.txt
/usr/share/openmpi/help-ras-slurm.txt
/usr/share/openmpi/help-rcache-base.txt
/usr/share/openmpi/help-regex.txt
/usr/share/openmpi/help-rmaps_rank_file.txt
/usr/share/openmpi/help-rtc-freq.txt
/usr/share/openmpi/help-shmem-api.txt
/usr/share/openmpi/help-shmem-runtime.txt
/usr/share/openmpi/help-state-staged-hnp.txt
/usr/share/openmpi/mpiCC-wrapper-data.txt
/usr/share/openmpi/mpic++-wrapper-data.txt
/usr/share/openmpi/mpicc-wrapper-data.txt
/usr/share/openmpi/mpicxx-wrapper-data.txt
/usr/share/openmpi/mpif77-wrapper-data.txt
/usr/share/openmpi/mpif90-wrapper-data.txt
/usr/share/openmpi/mpifort-wrapper-data.txt
/usr/share/openmpi/openmpi-valgrind.supp
/usr/share/openmpi/ortecc-wrapper-data.txt
/usr/share/openmpi/oshcc-wrapper-data.txt
/usr/share/openmpi/oshfort-wrapper-data.txt
/usr/share/openmpi/shmemcc-wrapper-data.txt
/usr/share/openmpi/shmemfort-wrapper-data.txt

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/mpp/shmem.fh
/usr/include/mpp/shmem.h
/usr/include/openmpi/ompi/mpiext/affinity/c/mpiext_affinity_c.h
/usr/include/openmpi/ompi/mpiext/cuda/c/mpiext_cuda_c.h
/usr/include/openshmem/oshmem/constants.h
/usr/include/openshmem/oshmem/frameworks.h
/usr/include/openshmem/oshmem/types.h
/usr/include/openshmem/oshmem/version.h
/usr/include/openshmem/oshmem_config.h
/usr/include/shmem.fh
/usr/lib64/libmca_common_sm.so
/usr/lib64/libmpi.so
/usr/lib64/libmpi_mpifh.so
/usr/lib64/libmpi_usempi_ignore_tkr.so
/usr/lib64/libmpi_usempif08.so
/usr/lib64/libompitrace.so
/usr/lib64/libopen-pal.so
/usr/lib64/libopen-rte.so
/usr/lib64/liboshmem.so
/usr/lib64/pkgconfig/ompi-c.pc
/usr/lib64/pkgconfig/ompi-cxx.pc
/usr/lib64/pkgconfig/ompi-f77.pc
/usr/lib64/pkgconfig/ompi-f90.pc
/usr/lib64/pkgconfig/ompi-fort.pc
/usr/lib64/pkgconfig/ompi.pc
/usr/lib64/pkgconfig/orte.pc
/usr/share/man/man3/MPI.3
/usr/share/man/man3/MPIX_Query_cuda_support.3
/usr/share/man/man3/MPI_Abort.3
/usr/share/man/man3/MPI_Accumulate.3
/usr/share/man/man3/MPI_Add_error_class.3
/usr/share/man/man3/MPI_Add_error_code.3
/usr/share/man/man3/MPI_Add_error_string.3
/usr/share/man/man3/MPI_Address.3
/usr/share/man/man3/MPI_Aint_add.3
/usr/share/man/man3/MPI_Aint_diff.3
/usr/share/man/man3/MPI_Allgather.3
/usr/share/man/man3/MPI_Allgatherv.3
/usr/share/man/man3/MPI_Alloc_mem.3
/usr/share/man/man3/MPI_Allreduce.3
/usr/share/man/man3/MPI_Alltoall.3
/usr/share/man/man3/MPI_Alltoallv.3
/usr/share/man/man3/MPI_Alltoallw.3
/usr/share/man/man3/MPI_Attr_delete.3
/usr/share/man/man3/MPI_Attr_get.3
/usr/share/man/man3/MPI_Attr_put.3
/usr/share/man/man3/MPI_Barrier.3
/usr/share/man/man3/MPI_Bcast.3
/usr/share/man/man3/MPI_Bsend.3
/usr/share/man/man3/MPI_Bsend_init.3
/usr/share/man/man3/MPI_Buffer_attach.3
/usr/share/man/man3/MPI_Buffer_detach.3
/usr/share/man/man3/MPI_Cancel.3
/usr/share/man/man3/MPI_Cart_coords.3
/usr/share/man/man3/MPI_Cart_create.3
/usr/share/man/man3/MPI_Cart_get.3
/usr/share/man/man3/MPI_Cart_map.3
/usr/share/man/man3/MPI_Cart_rank.3
/usr/share/man/man3/MPI_Cart_shift.3
/usr/share/man/man3/MPI_Cart_sub.3
/usr/share/man/man3/MPI_Cartdim_get.3
/usr/share/man/man3/MPI_Close_port.3
/usr/share/man/man3/MPI_Comm_accept.3
/usr/share/man/man3/MPI_Comm_c2f.3
/usr/share/man/man3/MPI_Comm_call_errhandler.3
/usr/share/man/man3/MPI_Comm_compare.3
/usr/share/man/man3/MPI_Comm_connect.3
/usr/share/man/man3/MPI_Comm_create.3
/usr/share/man/man3/MPI_Comm_create_errhandler.3
/usr/share/man/man3/MPI_Comm_create_group.3
/usr/share/man/man3/MPI_Comm_create_keyval.3
/usr/share/man/man3/MPI_Comm_delete_attr.3
/usr/share/man/man3/MPI_Comm_disconnect.3
/usr/share/man/man3/MPI_Comm_dup.3
/usr/share/man/man3/MPI_Comm_dup_with_info.3
/usr/share/man/man3/MPI_Comm_f2c.3
/usr/share/man/man3/MPI_Comm_free.3
/usr/share/man/man3/MPI_Comm_free_keyval.3
/usr/share/man/man3/MPI_Comm_get_attr.3
/usr/share/man/man3/MPI_Comm_get_errhandler.3
/usr/share/man/man3/MPI_Comm_get_info.3
/usr/share/man/man3/MPI_Comm_get_name.3
/usr/share/man/man3/MPI_Comm_get_parent.3
/usr/share/man/man3/MPI_Comm_group.3
/usr/share/man/man3/MPI_Comm_idup.3
/usr/share/man/man3/MPI_Comm_join.3
/usr/share/man/man3/MPI_Comm_rank.3
/usr/share/man/man3/MPI_Comm_remote_group.3
/usr/share/man/man3/MPI_Comm_remote_size.3
/usr/share/man/man3/MPI_Comm_set_attr.3
/usr/share/man/man3/MPI_Comm_set_errhandler.3
/usr/share/man/man3/MPI_Comm_set_info.3
/usr/share/man/man3/MPI_Comm_set_name.3
/usr/share/man/man3/MPI_Comm_size.3
/usr/share/man/man3/MPI_Comm_spawn.3
/usr/share/man/man3/MPI_Comm_spawn_multiple.3
/usr/share/man/man3/MPI_Comm_split.3
/usr/share/man/man3/MPI_Comm_split_type.3
/usr/share/man/man3/MPI_Comm_test_inter.3
/usr/share/man/man3/MPI_Compare_and_swap.3
/usr/share/man/man3/MPI_Dims_create.3
/usr/share/man/man3/MPI_Dist_graph_create.3
/usr/share/man/man3/MPI_Dist_graph_create_adjacent.3
/usr/share/man/man3/MPI_Dist_graph_neighbors.3
/usr/share/man/man3/MPI_Dist_graph_neighbors_count.3
/usr/share/man/man3/MPI_Errhandler_create.3
/usr/share/man/man3/MPI_Errhandler_free.3
/usr/share/man/man3/MPI_Errhandler_get.3
/usr/share/man/man3/MPI_Errhandler_set.3
/usr/share/man/man3/MPI_Error_class.3
/usr/share/man/man3/MPI_Error_string.3
/usr/share/man/man3/MPI_Exscan.3
/usr/share/man/man3/MPI_Fetch_and_op.3
/usr/share/man/man3/MPI_File_c2f.3
/usr/share/man/man3/MPI_File_call_errhandler.3
/usr/share/man/man3/MPI_File_close.3
/usr/share/man/man3/MPI_File_create_errhandler.3
/usr/share/man/man3/MPI_File_delete.3
/usr/share/man/man3/MPI_File_f2c.3
/usr/share/man/man3/MPI_File_get_amode.3
/usr/share/man/man3/MPI_File_get_atomicity.3
/usr/share/man/man3/MPI_File_get_byte_offset.3
/usr/share/man/man3/MPI_File_get_errhandler.3
/usr/share/man/man3/MPI_File_get_group.3
/usr/share/man/man3/MPI_File_get_info.3
/usr/share/man/man3/MPI_File_get_position.3
/usr/share/man/man3/MPI_File_get_position_shared.3
/usr/share/man/man3/MPI_File_get_size.3
/usr/share/man/man3/MPI_File_get_type_extent.3
/usr/share/man/man3/MPI_File_get_view.3
/usr/share/man/man3/MPI_File_iread.3
/usr/share/man/man3/MPI_File_iread_all.3
/usr/share/man/man3/MPI_File_iread_at.3
/usr/share/man/man3/MPI_File_iread_at_all.3
/usr/share/man/man3/MPI_File_iread_shared.3
/usr/share/man/man3/MPI_File_iwrite.3
/usr/share/man/man3/MPI_File_iwrite_all.3
/usr/share/man/man3/MPI_File_iwrite_at.3
/usr/share/man/man3/MPI_File_iwrite_at_all.3
/usr/share/man/man3/MPI_File_iwrite_shared.3
/usr/share/man/man3/MPI_File_open.3
/usr/share/man/man3/MPI_File_preallocate.3
/usr/share/man/man3/MPI_File_read.3
/usr/share/man/man3/MPI_File_read_all.3
/usr/share/man/man3/MPI_File_read_all_begin.3
/usr/share/man/man3/MPI_File_read_all_end.3
/usr/share/man/man3/MPI_File_read_at.3
/usr/share/man/man3/MPI_File_read_at_all.3
/usr/share/man/man3/MPI_File_read_at_all_begin.3
/usr/share/man/man3/MPI_File_read_at_all_end.3
/usr/share/man/man3/MPI_File_read_ordered.3
/usr/share/man/man3/MPI_File_read_ordered_begin.3
/usr/share/man/man3/MPI_File_read_ordered_end.3
/usr/share/man/man3/MPI_File_read_shared.3
/usr/share/man/man3/MPI_File_seek.3
/usr/share/man/man3/MPI_File_seek_shared.3
/usr/share/man/man3/MPI_File_set_atomicity.3
/usr/share/man/man3/MPI_File_set_errhandler.3
/usr/share/man/man3/MPI_File_set_info.3
/usr/share/man/man3/MPI_File_set_size.3
/usr/share/man/man3/MPI_File_set_view.3
/usr/share/man/man3/MPI_File_sync.3
/usr/share/man/man3/MPI_File_write.3
/usr/share/man/man3/MPI_File_write_all.3
/usr/share/man/man3/MPI_File_write_all_begin.3
/usr/share/man/man3/MPI_File_write_all_end.3
/usr/share/man/man3/MPI_File_write_at.3
/usr/share/man/man3/MPI_File_write_at_all.3
/usr/share/man/man3/MPI_File_write_at_all_begin.3
/usr/share/man/man3/MPI_File_write_at_all_end.3
/usr/share/man/man3/MPI_File_write_ordered.3
/usr/share/man/man3/MPI_File_write_ordered_begin.3
/usr/share/man/man3/MPI_File_write_ordered_end.3
/usr/share/man/man3/MPI_File_write_shared.3
/usr/share/man/man3/MPI_Finalize.3
/usr/share/man/man3/MPI_Finalized.3
/usr/share/man/man3/MPI_Free_mem.3
/usr/share/man/man3/MPI_Gather.3
/usr/share/man/man3/MPI_Gatherv.3
/usr/share/man/man3/MPI_Get.3
/usr/share/man/man3/MPI_Get_accumulate.3
/usr/share/man/man3/MPI_Get_address.3
/usr/share/man/man3/MPI_Get_count.3
/usr/share/man/man3/MPI_Get_elements.3
/usr/share/man/man3/MPI_Get_elements_x.3
/usr/share/man/man3/MPI_Get_library_version.3
/usr/share/man/man3/MPI_Get_processor_name.3
/usr/share/man/man3/MPI_Get_version.3
/usr/share/man/man3/MPI_Graph_create.3
/usr/share/man/man3/MPI_Graph_get.3
/usr/share/man/man3/MPI_Graph_map.3
/usr/share/man/man3/MPI_Graph_neighbors.3
/usr/share/man/man3/MPI_Graph_neighbors_count.3
/usr/share/man/man3/MPI_Graphdims_get.3
/usr/share/man/man3/MPI_Grequest_complete.3
/usr/share/man/man3/MPI_Grequest_start.3
/usr/share/man/man3/MPI_Group_c2f.3
/usr/share/man/man3/MPI_Group_compare.3
/usr/share/man/man3/MPI_Group_difference.3
/usr/share/man/man3/MPI_Group_excl.3
/usr/share/man/man3/MPI_Group_f2c.3
/usr/share/man/man3/MPI_Group_free.3
/usr/share/man/man3/MPI_Group_incl.3
/usr/share/man/man3/MPI_Group_intersection.3
/usr/share/man/man3/MPI_Group_range_excl.3
/usr/share/man/man3/MPI_Group_range_incl.3
/usr/share/man/man3/MPI_Group_rank.3
/usr/share/man/man3/MPI_Group_size.3
/usr/share/man/man3/MPI_Group_translate_ranks.3
/usr/share/man/man3/MPI_Group_union.3
/usr/share/man/man3/MPI_Iallgather.3
/usr/share/man/man3/MPI_Iallgatherv.3
/usr/share/man/man3/MPI_Iallreduce.3
/usr/share/man/man3/MPI_Ialltoall.3
/usr/share/man/man3/MPI_Ialltoallv.3
/usr/share/man/man3/MPI_Ialltoallw.3
/usr/share/man/man3/MPI_Ibarrier.3
/usr/share/man/man3/MPI_Ibcast.3
/usr/share/man/man3/MPI_Ibsend.3
/usr/share/man/man3/MPI_Iexscan.3
/usr/share/man/man3/MPI_Igather.3
/usr/share/man/man3/MPI_Igatherv.3
/usr/share/man/man3/MPI_Improbe.3
/usr/share/man/man3/MPI_Imrecv.3
/usr/share/man/man3/MPI_Ineighbor_allgather.3
/usr/share/man/man3/MPI_Ineighbor_allgatherv.3
/usr/share/man/man3/MPI_Ineighbor_alltoall.3
/usr/share/man/man3/MPI_Ineighbor_alltoallv.3
/usr/share/man/man3/MPI_Ineighbor_alltoallw.3
/usr/share/man/man3/MPI_Info_c2f.3
/usr/share/man/man3/MPI_Info_create.3
/usr/share/man/man3/MPI_Info_delete.3
/usr/share/man/man3/MPI_Info_dup.3
/usr/share/man/man3/MPI_Info_env.3
/usr/share/man/man3/MPI_Info_f2c.3
/usr/share/man/man3/MPI_Info_free.3
/usr/share/man/man3/MPI_Info_get.3
/usr/share/man/man3/MPI_Info_get_nkeys.3
/usr/share/man/man3/MPI_Info_get_nthkey.3
/usr/share/man/man3/MPI_Info_get_valuelen.3
/usr/share/man/man3/MPI_Info_set.3
/usr/share/man/man3/MPI_Init.3
/usr/share/man/man3/MPI_Init_thread.3
/usr/share/man/man3/MPI_Initialized.3
/usr/share/man/man3/MPI_Intercomm_create.3
/usr/share/man/man3/MPI_Intercomm_merge.3
/usr/share/man/man3/MPI_Iprobe.3
/usr/share/man/man3/MPI_Irecv.3
/usr/share/man/man3/MPI_Ireduce.3
/usr/share/man/man3/MPI_Ireduce_scatter.3
/usr/share/man/man3/MPI_Ireduce_scatter_block.3
/usr/share/man/man3/MPI_Irsend.3
/usr/share/man/man3/MPI_Is_thread_main.3
/usr/share/man/man3/MPI_Iscan.3
/usr/share/man/man3/MPI_Iscatter.3
/usr/share/man/man3/MPI_Iscatterv.3
/usr/share/man/man3/MPI_Isend.3
/usr/share/man/man3/MPI_Issend.3
/usr/share/man/man3/MPI_Keyval_create.3
/usr/share/man/man3/MPI_Keyval_free.3
/usr/share/man/man3/MPI_Lookup_name.3
/usr/share/man/man3/MPI_Message_c2f.3
/usr/share/man/man3/MPI_Message_f2c.3
/usr/share/man/man3/MPI_Mprobe.3
/usr/share/man/man3/MPI_Mrecv.3
/usr/share/man/man3/MPI_Neighbor_allgather.3
/usr/share/man/man3/MPI_Neighbor_allgatherv.3
/usr/share/man/man3/MPI_Neighbor_alltoall.3
/usr/share/man/man3/MPI_Neighbor_alltoallv.3
/usr/share/man/man3/MPI_Neighbor_alltoallw.3
/usr/share/man/man3/MPI_Op_c2f.3
/usr/share/man/man3/MPI_Op_commutative.3
/usr/share/man/man3/MPI_Op_create.3
/usr/share/man/man3/MPI_Op_f2c.3
/usr/share/man/man3/MPI_Op_free.3
/usr/share/man/man3/MPI_Open_port.3
/usr/share/man/man3/MPI_Pack.3
/usr/share/man/man3/MPI_Pack_external.3
/usr/share/man/man3/MPI_Pack_external_size.3
/usr/share/man/man3/MPI_Pack_size.3
/usr/share/man/man3/MPI_Pcontrol.3
/usr/share/man/man3/MPI_Probe.3
/usr/share/man/man3/MPI_Publish_name.3
/usr/share/man/man3/MPI_Put.3
/usr/share/man/man3/MPI_Query_thread.3
/usr/share/man/man3/MPI_Raccumulate.3
/usr/share/man/man3/MPI_Recv.3
/usr/share/man/man3/MPI_Recv_init.3
/usr/share/man/man3/MPI_Reduce.3
/usr/share/man/man3/MPI_Reduce_local.3
/usr/share/man/man3/MPI_Reduce_scatter.3
/usr/share/man/man3/MPI_Reduce_scatter_block.3
/usr/share/man/man3/MPI_Register_datarep.3
/usr/share/man/man3/MPI_Request_c2f.3
/usr/share/man/man3/MPI_Request_f2c.3
/usr/share/man/man3/MPI_Request_free.3
/usr/share/man/man3/MPI_Request_get_status.3
/usr/share/man/man3/MPI_Rget.3
/usr/share/man/man3/MPI_Rget_accumulate.3
/usr/share/man/man3/MPI_Rput.3
/usr/share/man/man3/MPI_Rsend.3
/usr/share/man/man3/MPI_Rsend_init.3
/usr/share/man/man3/MPI_Scan.3
/usr/share/man/man3/MPI_Scatter.3
/usr/share/man/man3/MPI_Scatterv.3
/usr/share/man/man3/MPI_Send.3
/usr/share/man/man3/MPI_Send_init.3
/usr/share/man/man3/MPI_Sendrecv.3
/usr/share/man/man3/MPI_Sendrecv_replace.3
/usr/share/man/man3/MPI_Sizeof.3
/usr/share/man/man3/MPI_Ssend.3
/usr/share/man/man3/MPI_Ssend_init.3
/usr/share/man/man3/MPI_Start.3
/usr/share/man/man3/MPI_Startall.3
/usr/share/man/man3/MPI_Status_c2f.3
/usr/share/man/man3/MPI_Status_f2c.3
/usr/share/man/man3/MPI_Status_set_cancelled.3
/usr/share/man/man3/MPI_Status_set_elements.3
/usr/share/man/man3/MPI_Status_set_elements_x.3
/usr/share/man/man3/MPI_T_category_changed.3
/usr/share/man/man3/MPI_T_category_get_categories.3
/usr/share/man/man3/MPI_T_category_get_cvars.3
/usr/share/man/man3/MPI_T_category_get_info.3
/usr/share/man/man3/MPI_T_category_get_num.3
/usr/share/man/man3/MPI_T_category_get_pvars.3
/usr/share/man/man3/MPI_T_cvar_get_info.3
/usr/share/man/man3/MPI_T_cvar_get_num.3
/usr/share/man/man3/MPI_T_cvar_handle_alloc.3
/usr/share/man/man3/MPI_T_cvar_handle_free.3
/usr/share/man/man3/MPI_T_cvar_read.3
/usr/share/man/man3/MPI_T_cvar_write.3
/usr/share/man/man3/MPI_T_enum_get_info.3
/usr/share/man/man3/MPI_T_enum_get_item.3
/usr/share/man/man3/MPI_T_finalize.3
/usr/share/man/man3/MPI_T_init_thread.3
/usr/share/man/man3/MPI_T_pvar_get_info.3
/usr/share/man/man3/MPI_T_pvar_get_num.3
/usr/share/man/man3/MPI_T_pvar_handle_alloc.3
/usr/share/man/man3/MPI_T_pvar_handle_free.3
/usr/share/man/man3/MPI_T_pvar_read.3
/usr/share/man/man3/MPI_T_pvar_readreset.3
/usr/share/man/man3/MPI_T_pvar_reset.3
/usr/share/man/man3/MPI_T_pvar_session_create.3
/usr/share/man/man3/MPI_T_pvar_session_free.3
/usr/share/man/man3/MPI_T_pvar_start.3
/usr/share/man/man3/MPI_T_pvar_stop.3
/usr/share/man/man3/MPI_T_pvar_write.3
/usr/share/man/man3/MPI_Test.3
/usr/share/man/man3/MPI_Test_cancelled.3
/usr/share/man/man3/MPI_Testall.3
/usr/share/man/man3/MPI_Testany.3
/usr/share/man/man3/MPI_Testsome.3
/usr/share/man/man3/MPI_Topo_test.3
/usr/share/man/man3/MPI_Type_c2f.3
/usr/share/man/man3/MPI_Type_commit.3
/usr/share/man/man3/MPI_Type_contiguous.3
/usr/share/man/man3/MPI_Type_create_darray.3
/usr/share/man/man3/MPI_Type_create_f90_complex.3
/usr/share/man/man3/MPI_Type_create_f90_integer.3
/usr/share/man/man3/MPI_Type_create_f90_real.3
/usr/share/man/man3/MPI_Type_create_hindexed.3
/usr/share/man/man3/MPI_Type_create_hindexed_block.3
/usr/share/man/man3/MPI_Type_create_hvector.3
/usr/share/man/man3/MPI_Type_create_indexed_block.3
/usr/share/man/man3/MPI_Type_create_keyval.3
/usr/share/man/man3/MPI_Type_create_resized.3
/usr/share/man/man3/MPI_Type_create_struct.3
/usr/share/man/man3/MPI_Type_create_subarray.3
/usr/share/man/man3/MPI_Type_delete_attr.3
/usr/share/man/man3/MPI_Type_dup.3
/usr/share/man/man3/MPI_Type_extent.3
/usr/share/man/man3/MPI_Type_f2c.3
/usr/share/man/man3/MPI_Type_free.3
/usr/share/man/man3/MPI_Type_free_keyval.3
/usr/share/man/man3/MPI_Type_get_attr.3
/usr/share/man/man3/MPI_Type_get_contents.3
/usr/share/man/man3/MPI_Type_get_envelope.3
/usr/share/man/man3/MPI_Type_get_extent.3
/usr/share/man/man3/MPI_Type_get_extent_x.3
/usr/share/man/man3/MPI_Type_get_name.3
/usr/share/man/man3/MPI_Type_get_true_extent.3
/usr/share/man/man3/MPI_Type_get_true_extent_x.3
/usr/share/man/man3/MPI_Type_hindexed.3
/usr/share/man/man3/MPI_Type_hvector.3
/usr/share/man/man3/MPI_Type_indexed.3
/usr/share/man/man3/MPI_Type_lb.3
/usr/share/man/man3/MPI_Type_match_size.3
/usr/share/man/man3/MPI_Type_set_attr.3
/usr/share/man/man3/MPI_Type_set_name.3
/usr/share/man/man3/MPI_Type_size.3
/usr/share/man/man3/MPI_Type_size_x.3
/usr/share/man/man3/MPI_Type_struct.3
/usr/share/man/man3/MPI_Type_ub.3
/usr/share/man/man3/MPI_Type_vector.3
/usr/share/man/man3/MPI_Unpack.3
/usr/share/man/man3/MPI_Unpack_external.3
/usr/share/man/man3/MPI_Unpublish_name.3
/usr/share/man/man3/MPI_Wait.3
/usr/share/man/man3/MPI_Waitall.3
/usr/share/man/man3/MPI_Waitany.3
/usr/share/man/man3/MPI_Waitsome.3
/usr/share/man/man3/MPI_Win_allocate.3
/usr/share/man/man3/MPI_Win_allocate_shared.3
/usr/share/man/man3/MPI_Win_attach.3
/usr/share/man/man3/MPI_Win_c2f.3
/usr/share/man/man3/MPI_Win_call_errhandler.3
/usr/share/man/man3/MPI_Win_complete.3
/usr/share/man/man3/MPI_Win_create.3
/usr/share/man/man3/MPI_Win_create_dynamic.3
/usr/share/man/man3/MPI_Win_create_errhandler.3
/usr/share/man/man3/MPI_Win_create_keyval.3
/usr/share/man/man3/MPI_Win_delete_attr.3
/usr/share/man/man3/MPI_Win_detach.3
/usr/share/man/man3/MPI_Win_f2c.3
/usr/share/man/man3/MPI_Win_fence.3
/usr/share/man/man3/MPI_Win_flush.3
/usr/share/man/man3/MPI_Win_flush_all.3
/usr/share/man/man3/MPI_Win_flush_local.3
/usr/share/man/man3/MPI_Win_flush_local_all.3
/usr/share/man/man3/MPI_Win_free.3
/usr/share/man/man3/MPI_Win_free_keyval.3
/usr/share/man/man3/MPI_Win_get_attr.3
/usr/share/man/man3/MPI_Win_get_errhandler.3
/usr/share/man/man3/MPI_Win_get_group.3
/usr/share/man/man3/MPI_Win_get_info.3
/usr/share/man/man3/MPI_Win_get_name.3
/usr/share/man/man3/MPI_Win_lock.3
/usr/share/man/man3/MPI_Win_lock_all.3
/usr/share/man/man3/MPI_Win_post.3
/usr/share/man/man3/MPI_Win_set_attr.3
/usr/share/man/man3/MPI_Win_set_errhandler.3
/usr/share/man/man3/MPI_Win_set_info.3
/usr/share/man/man3/MPI_Win_set_name.3
/usr/share/man/man3/MPI_Win_shared_query.3
/usr/share/man/man3/MPI_Win_start.3
/usr/share/man/man3/MPI_Win_sync.3
/usr/share/man/man3/MPI_Win_test.3
/usr/share/man/man3/MPI_Win_unlock.3
/usr/share/man/man3/MPI_Win_unlock_all.3
/usr/share/man/man3/MPI_Win_wait.3
/usr/share/man/man3/MPI_Wtick.3
/usr/share/man/man3/MPI_Wtime.3
/usr/share/man/man3/OMPI_Affinity_str.3
/usr/share/man/man3/OpenMPI.3
/usr/share/man/man3/OpenSHMEM.3
/usr/share/man/man3/_my_pe.3
/usr/share/man/man3/_num_pes.3
/usr/share/man/man3/intro_shmem.3
/usr/share/man/man3/shfree.3
/usr/share/man/man3/shmalloc.3
/usr/share/man/man3/shmem_addr_accessible.3
/usr/share/man/man3/shmem_align.3
/usr/share/man/man3/shmem_alltoall32.3
/usr/share/man/man3/shmem_alltoall64.3
/usr/share/man/man3/shmem_alltoalls32.3
/usr/share/man/man3/shmem_alltoalls64.3
/usr/share/man/man3/shmem_barrier.3
/usr/share/man/man3/shmem_barrier_all.3
/usr/share/man/man3/shmem_broadcast32.3
/usr/share/man/man3/shmem_broadcast64.3
/usr/share/man/man3/shmem_char_g.3
/usr/share/man/man3/shmem_char_get.3
/usr/share/man/man3/shmem_char_get_nbi.3
/usr/share/man/man3/shmem_char_p.3
/usr/share/man/man3/shmem_char_put.3
/usr/share/man/man3/shmem_char_put_nbi.3
/usr/share/man/man3/shmem_clear_cache_inv.3
/usr/share/man/man3/shmem_clear_cache_line_inv.3
/usr/share/man/man3/shmem_clear_lock.3
/usr/share/man/man3/shmem_collect32.3
/usr/share/man/man3/shmem_collect64.3
/usr/share/man/man3/shmem_complexd_prod_to_all.3
/usr/share/man/man3/shmem_complexd_sum_to_all.3
/usr/share/man/man3/shmem_complexf_prod_to_all.3
/usr/share/man/man3/shmem_complexf_sum_to_all.3
/usr/share/man/man3/shmem_double_fetch.3
/usr/share/man/man3/shmem_double_g.3
/usr/share/man/man3/shmem_double_get.3
/usr/share/man/man3/shmem_double_get_nbi.3
/usr/share/man/man3/shmem_double_iget.3
/usr/share/man/man3/shmem_double_iput.3
/usr/share/man/man3/shmem_double_max_to_all.3
/usr/share/man/man3/shmem_double_min_to_all.3
/usr/share/man/man3/shmem_double_p.3
/usr/share/man/man3/shmem_double_prod_to_all.3
/usr/share/man/man3/shmem_double_put.3
/usr/share/man/man3/shmem_double_put_nbi.3
/usr/share/man/man3/shmem_double_set.3
/usr/share/man/man3/shmem_double_sum_to_all.3
/usr/share/man/man3/shmem_double_swap.3
/usr/share/man/man3/shmem_fcollect32.3
/usr/share/man/man3/shmem_fcollect64.3
/usr/share/man/man3/shmem_fence.3
/usr/share/man/man3/shmem_finalize.3
/usr/share/man/man3/shmem_float_fetch.3
/usr/share/man/man3/shmem_float_g.3
/usr/share/man/man3/shmem_float_get.3
/usr/share/man/man3/shmem_float_get_nbi.3
/usr/share/man/man3/shmem_float_iget.3
/usr/share/man/man3/shmem_float_iput.3
/usr/share/man/man3/shmem_float_max_to_all.3
/usr/share/man/man3/shmem_float_min_to_all.3
/usr/share/man/man3/shmem_float_p.3
/usr/share/man/man3/shmem_float_prod_to_all.3
/usr/share/man/man3/shmem_float_put.3
/usr/share/man/man3/shmem_float_put_nbi.3
/usr/share/man/man3/shmem_float_set.3
/usr/share/man/man3/shmem_float_sum_to_all.3
/usr/share/man/man3/shmem_float_swap.3
/usr/share/man/man3/shmem_free.3
/usr/share/man/man3/shmem_get128.3
/usr/share/man/man3/shmem_get128_nbi.3
/usr/share/man/man3/shmem_get16_nbi.3
/usr/share/man/man3/shmem_get32.3
/usr/share/man/man3/shmem_get32_nbi.3
/usr/share/man/man3/shmem_get64.3
/usr/share/man/man3/shmem_get64_nbi.3
/usr/share/man/man3/shmem_get8_nbi.3
/usr/share/man/man3/shmem_getmem.3
/usr/share/man/man3/shmem_getmem_nbi.3
/usr/share/man/man3/shmem_global_exit.3
/usr/share/man/man3/shmem_iget128.3
/usr/share/man/man3/shmem_iget32.3
/usr/share/man/man3/shmem_iget64.3
/usr/share/man/man3/shmem_info_get_name.3
/usr/share/man/man3/shmem_info_get_version.3
/usr/share/man/man3/shmem_init.3
/usr/share/man/man3/shmem_int_add.3
/usr/share/man/man3/shmem_int_and_to_all.3
/usr/share/man/man3/shmem_int_cswap.3
/usr/share/man/man3/shmem_int_fadd.3
/usr/share/man/man3/shmem_int_fetch.3
/usr/share/man/man3/shmem_int_finc.3
/usr/share/man/man3/shmem_int_g.3
/usr/share/man/man3/shmem_int_get.3
/usr/share/man/man3/shmem_int_get_nbi.3
/usr/share/man/man3/shmem_int_iget.3
/usr/share/man/man3/shmem_int_inc.3
/usr/share/man/man3/shmem_int_iput.3
/usr/share/man/man3/shmem_int_max_to_all.3
/usr/share/man/man3/shmem_int_min_to_all.3
/usr/share/man/man3/shmem_int_or_to_all.3
/usr/share/man/man3/shmem_int_p.3
/usr/share/man/man3/shmem_int_prod_to_all.3
/usr/share/man/man3/shmem_int_put.3
/usr/share/man/man3/shmem_int_put_nbi.3
/usr/share/man/man3/shmem_int_set.3
/usr/share/man/man3/shmem_int_sum_to_all.3
/usr/share/man/man3/shmem_int_swap.3
/usr/share/man/man3/shmem_int_wait.3
/usr/share/man/man3/shmem_int_wait_until.3
/usr/share/man/man3/shmem_int_xor_to_all.3
/usr/share/man/man3/shmem_iput128.3
/usr/share/man/man3/shmem_iput32.3
/usr/share/man/man3/shmem_iput64.3
/usr/share/man/man3/shmem_long_add.3
/usr/share/man/man3/shmem_long_and_to_all.3
/usr/share/man/man3/shmem_long_cswap.3
/usr/share/man/man3/shmem_long_fadd.3
/usr/share/man/man3/shmem_long_fetch.3
/usr/share/man/man3/shmem_long_finc.3
/usr/share/man/man3/shmem_long_g.3
/usr/share/man/man3/shmem_long_get.3
/usr/share/man/man3/shmem_long_get_nbi.3
/usr/share/man/man3/shmem_long_iget.3
/usr/share/man/man3/shmem_long_inc.3
/usr/share/man/man3/shmem_long_iput.3
/usr/share/man/man3/shmem_long_max_to_all.3
/usr/share/man/man3/shmem_long_min_to_all.3
/usr/share/man/man3/shmem_long_or_to_all.3
/usr/share/man/man3/shmem_long_p.3
/usr/share/man/man3/shmem_long_prod_to_all.3
/usr/share/man/man3/shmem_long_put.3
/usr/share/man/man3/shmem_long_put_nbi.3
/usr/share/man/man3/shmem_long_set.3
/usr/share/man/man3/shmem_long_sum_to_all.3
/usr/share/man/man3/shmem_long_swap.3
/usr/share/man/man3/shmem_long_wait.3
/usr/share/man/man3/shmem_long_wait_until.3
/usr/share/man/man3/shmem_long_xor_to_all.3
/usr/share/man/man3/shmem_longdouble_g.3
/usr/share/man/man3/shmem_longdouble_get.3
/usr/share/man/man3/shmem_longdouble_get_nbi.3
/usr/share/man/man3/shmem_longdouble_iget.3
/usr/share/man/man3/shmem_longdouble_iput.3
/usr/share/man/man3/shmem_longdouble_max_to_all.3
/usr/share/man/man3/shmem_longdouble_min_to_all.3
/usr/share/man/man3/shmem_longdouble_p.3
/usr/share/man/man3/shmem_longdouble_prod_to_all.3
/usr/share/man/man3/shmem_longdouble_put.3
/usr/share/man/man3/shmem_longdouble_put_nbi.3
/usr/share/man/man3/shmem_longlong_add.3
/usr/share/man/man3/shmem_longlong_and_to_all.3
/usr/share/man/man3/shmem_longlong_cswap.3
/usr/share/man/man3/shmem_longlong_fadd.3
/usr/share/man/man3/shmem_longlong_fetch.3
/usr/share/man/man3/shmem_longlong_finc.3
/usr/share/man/man3/shmem_longlong_g.3
/usr/share/man/man3/shmem_longlong_get.3
/usr/share/man/man3/shmem_longlong_get_nbi.3
/usr/share/man/man3/shmem_longlong_iget.3
/usr/share/man/man3/shmem_longlong_inc.3
/usr/share/man/man3/shmem_longlong_iput.3
/usr/share/man/man3/shmem_longlong_max_to_all.3
/usr/share/man/man3/shmem_longlong_min_to_all.3
/usr/share/man/man3/shmem_longlong_or_to_all.3
/usr/share/man/man3/shmem_longlong_p.3
/usr/share/man/man3/shmem_longlong_prod_to_all.3
/usr/share/man/man3/shmem_longlong_put.3
/usr/share/man/man3/shmem_longlong_put_nbi.3
/usr/share/man/man3/shmem_longlong_set.3
/usr/share/man/man3/shmem_longlong_sum_to_all.3
/usr/share/man/man3/shmem_longlong_swap.3
/usr/share/man/man3/shmem_longlong_wait.3
/usr/share/man/man3/shmem_longlong_wait_until.3
/usr/share/man/man3/shmem_longlong_xor_to_all.3
/usr/share/man/man3/shmem_malloc.3
/usr/share/man/man3/shmem_my_pe.3
/usr/share/man/man3/shmem_n_pes.3
/usr/share/man/man3/shmem_pe_accessible.3
/usr/share/man/man3/shmem_ptr.3
/usr/share/man/man3/shmem_put128.3
/usr/share/man/man3/shmem_put128_nbi.3
/usr/share/man/man3/shmem_put16_nbi.3
/usr/share/man/man3/shmem_put32.3
/usr/share/man/man3/shmem_put32_nbi.3
/usr/share/man/man3/shmem_put64.3
/usr/share/man/man3/shmem_put64_nbi.3
/usr/share/man/man3/shmem_put8_nbi.3
/usr/share/man/man3/shmem_putmem.3
/usr/share/man/man3/shmem_putmem_nbi.3
/usr/share/man/man3/shmem_quiet.3
/usr/share/man/man3/shmem_realloc.3
/usr/share/man/man3/shmem_set_cache_inv.3
/usr/share/man/man3/shmem_set_cache_line_inv.3
/usr/share/man/man3/shmem_set_lock.3
/usr/share/man/man3/shmem_short_and_to_all.3
/usr/share/man/man3/shmem_short_g.3
/usr/share/man/man3/shmem_short_get.3
/usr/share/man/man3/shmem_short_get_nbi.3
/usr/share/man/man3/shmem_short_iget.3
/usr/share/man/man3/shmem_short_iput.3
/usr/share/man/man3/shmem_short_max_to_all.3
/usr/share/man/man3/shmem_short_min_to_all.3
/usr/share/man/man3/shmem_short_or_to_all.3
/usr/share/man/man3/shmem_short_p.3
/usr/share/man/man3/shmem_short_prod_to_all.3
/usr/share/man/man3/shmem_short_put.3
/usr/share/man/man3/shmem_short_put_nbi.3
/usr/share/man/man3/shmem_short_sum_to_all.3
/usr/share/man/man3/shmem_short_wait.3
/usr/share/man/man3/shmem_short_wait_until.3
/usr/share/man/man3/shmem_short_xor_to_all.3
/usr/share/man/man3/shmem_swap.3
/usr/share/man/man3/shmem_test_lock.3
/usr/share/man/man3/shmem_udcflush.3
/usr/share/man/man3/shmem_udcflush_line.3
/usr/share/man/man3/shmem_wait.3
/usr/share/man/man3/shmem_wait_until.3
/usr/share/man/man3/shmemalign.3
/usr/share/man/man3/shrealloc.3
/usr/share/man/man3/start_pes.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmca_common_sm.so.20
/usr/lib64/libmca_common_sm.so.20.10.1
/usr/lib64/libmpi.so.20
/usr/lib64/libmpi.so.20.10.2
/usr/lib64/libmpi_mpifh.so.20
/usr/lib64/libmpi_mpifh.so.20.12.0
/usr/lib64/libmpi_usempi_ignore_tkr.so.20
/usr/lib64/libmpi_usempi_ignore_tkr.so.20.11.0
/usr/lib64/libmpi_usempif08.so.20
/usr/lib64/libmpi_usempif08.so.20.11.0
/usr/lib64/libompitrace.so.20
/usr/lib64/libompitrace.so.20.10.0
/usr/lib64/libopen-pal.so.20
/usr/lib64/libopen-pal.so.20.10.3
/usr/lib64/libopen-rte.so.20
/usr/lib64/libopen-rte.so.20.10.3
/usr/lib64/liboshmem.so.20
/usr/lib64/liboshmem.so.20.10.2
/usr/lib64/openmpi/libompi_dbg_msgq.so
/usr/lib64/openmpi/mca_allocator_basic.so
/usr/lib64/openmpi/mca_allocator_bucket.so
/usr/lib64/openmpi/mca_atomic_basic.so
/usr/lib64/openmpi/mca_bml_r2.so
/usr/lib64/openmpi/mca_btl_self.so
/usr/lib64/openmpi/mca_btl_sm.so
/usr/lib64/openmpi/mca_btl_tcp.so
/usr/lib64/openmpi/mca_btl_vader.so
/usr/lib64/openmpi/mca_coll_basic.so
/usr/lib64/openmpi/mca_coll_inter.so
/usr/lib64/openmpi/mca_coll_libnbc.so
/usr/lib64/openmpi/mca_coll_self.so
/usr/lib64/openmpi/mca_coll_sm.so
/usr/lib64/openmpi/mca_coll_sync.so
/usr/lib64/openmpi/mca_coll_tuned.so
/usr/lib64/openmpi/mca_dfs_app.so
/usr/lib64/openmpi/mca_dfs_orted.so
/usr/lib64/openmpi/mca_dfs_test.so
/usr/lib64/openmpi/mca_errmgr_default_app.so
/usr/lib64/openmpi/mca_errmgr_default_hnp.so
/usr/lib64/openmpi/mca_errmgr_default_orted.so
/usr/lib64/openmpi/mca_errmgr_default_tool.so
/usr/lib64/openmpi/mca_ess_env.so
/usr/lib64/openmpi/mca_ess_hnp.so
/usr/lib64/openmpi/mca_ess_pmi.so
/usr/lib64/openmpi/mca_ess_singleton.so
/usr/lib64/openmpi/mca_ess_slurm.so
/usr/lib64/openmpi/mca_ess_tool.so
/usr/lib64/openmpi/mca_fbtl_posix.so
/usr/lib64/openmpi/mca_fcoll_dynamic.so
/usr/lib64/openmpi/mca_fcoll_dynamic_gen2.so
/usr/lib64/openmpi/mca_fcoll_individual.so
/usr/lib64/openmpi/mca_fcoll_static.so
/usr/lib64/openmpi/mca_fcoll_two_phase.so
/usr/lib64/openmpi/mca_filem_raw.so
/usr/lib64/openmpi/mca_fs_ufs.so
/usr/lib64/openmpi/mca_grpcomm_direct.so
/usr/lib64/openmpi/mca_io_ompio.so
/usr/lib64/openmpi/mca_io_romio314.so
/usr/lib64/openmpi/mca_iof_hnp.so
/usr/lib64/openmpi/mca_iof_mr_hnp.so
/usr/lib64/openmpi/mca_iof_mr_orted.so
/usr/lib64/openmpi/mca_iof_orted.so
/usr/lib64/openmpi/mca_iof_tool.so
/usr/lib64/openmpi/mca_memheap_buddy.so
/usr/lib64/openmpi/mca_memheap_ptmalloc.so
/usr/lib64/openmpi/mca_mpool_hugepage.so
/usr/lib64/openmpi/mca_notifier_syslog.so
/usr/lib64/openmpi/mca_odls_default.so
/usr/lib64/openmpi/mca_oob_tcp.so
/usr/lib64/openmpi/mca_oob_usock.so
/usr/lib64/openmpi/mca_osc_pt2pt.so
/usr/lib64/openmpi/mca_osc_rdma.so
/usr/lib64/openmpi/mca_osc_sm.so
/usr/lib64/openmpi/mca_patcher_overwrite.so
/usr/lib64/openmpi/mca_plm_isolated.so
/usr/lib64/openmpi/mca_plm_rsh.so
/usr/lib64/openmpi/mca_plm_slurm.so
/usr/lib64/openmpi/mca_pmix_pmix112.so
/usr/lib64/openmpi/mca_pml_cm.so
/usr/lib64/openmpi/mca_pml_ob1.so
/usr/lib64/openmpi/mca_pstat_linux.so
/usr/lib64/openmpi/mca_ras_loadleveler.so
/usr/lib64/openmpi/mca_ras_simulator.so
/usr/lib64/openmpi/mca_ras_slurm.so
/usr/lib64/openmpi/mca_rcache_grdma.so
/usr/lib64/openmpi/mca_rmaps_mindist.so
/usr/lib64/openmpi/mca_rmaps_ppr.so
/usr/lib64/openmpi/mca_rmaps_rank_file.so
/usr/lib64/openmpi/mca_rmaps_resilient.so
/usr/lib64/openmpi/mca_rmaps_round_robin.so
/usr/lib64/openmpi/mca_rmaps_seq.so
/usr/lib64/openmpi/mca_rmaps_staged.so
/usr/lib64/openmpi/mca_rml_oob.so
/usr/lib64/openmpi/mca_routed_binomial.so
/usr/lib64/openmpi/mca_routed_debruijn.so
/usr/lib64/openmpi/mca_routed_direct.so
/usr/lib64/openmpi/mca_routed_radix.so
/usr/lib64/openmpi/mca_rtc_freq.so
/usr/lib64/openmpi/mca_rtc_hwloc.so
/usr/lib64/openmpi/mca_schizo_ompi.so
/usr/lib64/openmpi/mca_scoll_basic.so
/usr/lib64/openmpi/mca_scoll_mpi.so
/usr/lib64/openmpi/mca_sec_basic.so
/usr/lib64/openmpi/mca_sharedfp_individual.so
/usr/lib64/openmpi/mca_sharedfp_lockedfile.so
/usr/lib64/openmpi/mca_sharedfp_sm.so
/usr/lib64/openmpi/mca_shmem_mmap.so
/usr/lib64/openmpi/mca_shmem_posix.so
/usr/lib64/openmpi/mca_shmem_sysv.so
/usr/lib64/openmpi/mca_spml_yoda.so
/usr/lib64/openmpi/mca_sshmem_mmap.so
/usr/lib64/openmpi/mca_sshmem_sysv.so
/usr/lib64/openmpi/mca_state_app.so
/usr/lib64/openmpi/mca_state_dvm.so
/usr/lib64/openmpi/mca_state_hnp.so
/usr/lib64/openmpi/mca_state_novm.so
/usr/lib64/openmpi/mca_state_orted.so
/usr/lib64/openmpi/mca_state_staged_hnp.so
/usr/lib64/openmpi/mca_state_staged_orted.so
/usr/lib64/openmpi/mca_state_tool.so
/usr/lib64/openmpi/mca_topo_basic.so
/usr/lib64/openmpi/mca_vprotocol_pessimist.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/openmpi/LICENSE
/usr/share/package-licenses/openmpi/contrib_dist_mofed_debian_copyright
/usr/share/package-licenses/openmpi/opal_mca_event_libevent2022_libevent_LICENSE
/usr/share/package-licenses/openmpi/opal_mca_hwloc_hwloc1112_hwloc_COPYING
/usr/share/package-licenses/openmpi/opal_mca_pmix_pmix112_pmix_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mpiCC.1
/usr/share/man/man1/mpic++.1
/usr/share/man/man1/mpicc.1
/usr/share/man/man1/mpicxx.1
/usr/share/man/man1/mpiexec.1
/usr/share/man/man1/mpif77.1
/usr/share/man/man1/mpif90.1
/usr/share/man/man1/mpifort.1
/usr/share/man/man1/mpirun.1
/usr/share/man/man1/ompi-clean.1
/usr/share/man/man1/ompi-dvm.1
/usr/share/man/man1/ompi-ps.1
/usr/share/man/man1/ompi-server.1
/usr/share/man/man1/ompi-submit.1
/usr/share/man/man1/ompi-top.1
/usr/share/man/man1/ompi_info.1
/usr/share/man/man1/opal_wrapper.1
/usr/share/man/man1/orte-clean.1
/usr/share/man/man1/orte-dvm.1
/usr/share/man/man1/orte-info.1
/usr/share/man/man1/orte-ps.1
/usr/share/man/man1/orte-server.1
/usr/share/man/man1/orte-submit.1
/usr/share/man/man1/orte-top.1
/usr/share/man/man1/orted.1
/usr/share/man/man1/orterun.1
/usr/share/man/man1/oshcc.1
/usr/share/man/man1/oshfort.1
/usr/share/man/man1/oshmem_info.1
/usr/share/man/man1/oshrun.1
/usr/share/man/man1/shmemcc.1
/usr/share/man/man1/shmemfort.1
/usr/share/man/man1/shmemrun.1
/usr/share/man/man7/orte_filem.7
/usr/share/man/man7/orte_hosts.7
